### ISSUE TITLE
actor/commands

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmagp#11]
... in the actor/commands section there should only be a minimum of code, everything else should be in an extra module outside of the actor module.

Dont put algorithmic code like [this](https://github.com/sdss/lvmagp/blob/12791e7a10dca3ed97bd0d1f566677685652d30f/python/lvmagp/actor/commands/autofocus.py#L23) here, its way to complicated to test it.

**Comment by HojaeAhn** [comment]
It proceeds with the development of lvmagp API. Once API is completed, we just import the API and use it in actor/commands.
