### ISSUE TITLE
Dont put testing code in the actor

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmagp#12]
Remove stuff like [KHU_inner_test](https://github.com/sdss/lvmagp/blob/12791e7a10dca3ed97bd0d1f566677685652d30f/python/lvmagp/actor/commands/guide.py#L11) or ["test.first.focus_stage"](https://github.com/sdss/lvmagp/blob/12791e7a10dca3ed97bd0d1f566677685652d30f/python/lvmagp/actor/commfunc.py#L11) or [fits files](https://github.com/sdss/lvmagp/blob/12791e7a10dca3ed97bd0d1f566677685652d30f/python/lvmagp/actor/commands/autofocus.py#L35) 

Some people might disagree, but I do not like _if test = True then do that_, it makes code unreadable and dangerous.

It whould be better that lvmcam supports a virtual camera [see 
](https://github.com/sdss/lvmcam/issues/49) or that all algorithmic functionality can be tested from outside the actor.

**Comment by HojaeAhn** [comment]
We are organizing the algorithm code in commfunc.py, removing the test codes.
