### ISSUE TITLE
Create a focus module with tests outside of the actor commands.

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmagp#13]
* Remove actor/commands/autofocus.py and put the three actor interface commands for calling the members of the following module in actor/commands/focus.py
* Create a focus module outside of the actor directory tree as a module. Parameters as a config subtree from global config(focus actor name, ...)
  - manual focus offset - [see](https://github.com/sdss/lvmops/blob/9221617bf1fb3ebe4fe908462ea5d026b69a0716/lvmops/tel_interface.py#L128)
  - focus by temperature - [see](https://github.com/sdss/lvmops/blob/9221617bf1fb3ebe4fe908462ea5d026b69a0716/lvmops/tel_interface.py#L137)
  - autofocus - [see](https://github.com/sdss/lvmops/blob/9221617bf1fb3ebe4fe908462ea5d026b69a0716/lvmops/tel_interface.py#L121)
* Add regression tests for the focus module, maybe with the images from testimg/ already included in the package.

**Comment by HojaeAhn** [comment]
commfunc.py corresponds to the focus module (integrated module, actually) in your comment.
I think this kind of job is also needed for kmirror and fiber selector. I'll do it for them when it is ready.
