### ISSUE TITLE
Use astropy

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmagp#14]
... instead of writing tiny methods [deg_to_dms](https://github.com/sdss/lvmagp/blob/12791e7a10dca3ed97bd0d1f566677685652d30f/python/lvmagp/actor/commands/slew.py#L12), 

https://docs.astropy.org/en/stable/coordinates/angles.html#working-with-angles

from astropy import units as u
from astropy.coordinates import Angle

coordinates.Angle(10*u.deg).dms

**Comment by HojaeAhn** [comment]
The code is revised based on your advice.
