### ISSUE TITLE
Create a aquisition module with tests outside of the actor commands.

### ISSUE THREAD

**Issue by wasndas** [sdss/lvmagp#15]
Similar to the [focus part](https://github.com/sdss/lvmagp/issues/13), remove the algorithmic part from the actor/commands,eg  find_stars.

1. imaging - [expose](https://github.com/sdss/lvmops/blob/9221617bf1fb3ebe4fe908462ea5d026b69a0716/lvmops/agc_interface.py#L26), [bias](https://github.com/sdss/lvmops/blob/9221617bf1fb3ebe4fe908462ea5d026b69a0716/lvmops/agc_interface.py#L41) 
2. finding stars - use/est differnet algorithms, [DAOStarFinder & IRAFStarFinder](https://photutils.readthedocs.io/en/stable/detection.html), [SEP](https://github.com/kbarbary/sep) with configuration parameter from config as default.
3. astrometry
4. ...

**Comment by HojaeAhn** [comment]
It is in a similiar case to the focus as you mentioned.
I made commfunc.py as the integrated module. It contains both the focus part and the acquisition part.
